export const MerchandasingData = {
    gorraText: "NVIKK's Logo Cap",
    tazaText: "NVIKK's Logo Cup",
    camisetaText: "No NVIKK No Party T-shirt",
    bolsaText: "No NVIKK No Party Bag",
    altGorra: "NVIKK's Logo Cap ",
    altTaza: "NVIKK's Logo Cup ",
    altBolsa: "No NVIKK No Party Bag",
    altCamisetaFront: "No NVIKK No Party T-shirt front",
    altCamisetaBack: "No NVIKK No Party T-shirt back",
    imgCamisetaFront: require('../../images/camiseta_delante.jpeg'),
    imgCamisetaBack: require('../../images/camiseta_detras.jpeg'),
    imgBolsa: require('../../images/mochila_negra.PNG'),
    camisetaPrecio: '20.00 $',
    gorraPrecio: '10.00 $',
    bolsaPrecio: '15.50 $',
    tazaPrecio: '11.50 $',
    purchaseText: 'Order it now',
}