export const musicObjOne = {
  id: "music",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Music",
  playlistText: "Follow our EDM Playlist on Spotify",
  latestText: "Latest uploads",
  favText: "Favorite songs",
  imgStart: false,
  img: require("../../images/NVIKK_NOPARTY.jpg"),
  imgLastUpload1: require("../../images/Session5.PNG"),
  imgLastUpload2: require("../../images/RollingintheclubNVIKK.png"),
  imgLastUpload3: require("../../images/HotGirlLier.PNG"),
  imgFavSongs1: require("../../images/Mako_ourStory.jpg"),
  imgFavSongs2: require("../../images/revealed7.jfif"),
  imgFavSongs3: require("../../images/tiesto-ava-max-the-motto.jpg"),
  altLastUpload1: "Last session upload",
  altLastUpload2: "Last mashup upload",
  altFavSongs1: "Mako - our story",
  altFavSongs2: "Hardwell revealed 7",
  altFavSongs3: "Tïesto - The Motto",
  uriLastUpload1: "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1121620984&color=%231e202e&auto_play=false&hide_related=false&show_comments=false&show_user=false&show_reposts=false&show_teaser=false&visual=true",
  uriLastUpload2: "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1148994916&color=%231e202e&auto_play=false&hide_related=false&show_comments=false&show_user=false&show_reposts=false&show_teaser=false&visual=true",
  uriLastUpload3: "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1125649681&color=%231e202e&auto_play=false&hide_related=false&show_comments=false&show_user=false&show_reposts=false&show_teaser=false&visual=true",
  uriFavSong1: "https://open.spotify.com/embed/album/51MD9xGLAuDSg461VqVCYh?utm_source=generator",
  uriFavSong2: "https://open.spotify.com/embed/album/0iOWjP0KD6bClZ1a5rQ8yK?utm_source=generator",
  uriFavSong3: "https://open.spotify.com/embed/album/278z9UXJaMNDH9Bel9uAxV?utm_source=generator",
  alt: "NO NVIKK NO PARTY LOGO",
  dark: true,
  primary: true,
  darkText: false,
};
